version: '3.4'
services:
  dsslam:
    image: yubaoliu/ds_slam:kinetic
    network_mode: host
    build:
        context: .
        network: host
    container_name: dsslam
    privileged: true
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu, utility]
    command: xterm
         # lxterminal
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ../:/root/catkin_ws/src/DS-SLAM
        - ${DATASET_DIR}:/root/Dataset
        # - orbslam3:/root
    entrypoint: /ros_entrypoint.sh
# volumes:
     # dsslam:
